### ISSUE TITLE
用PFE自带的领地插件，文件里没有数据

### ISSUE THREAD

**Issue by threestarsQAQ** [littlegao233/PFEssentials-Release#10]
玩家在游戏里创建领地或者warp，文件里没有数据，导致重启后谁据丢失

**Comment by LazuliKao** [comment]
![image](https://user-images.githubusercontent.com/46601807/173166704-20ec139b-417d-4c0b-b005-4efe22833ff6.png)
文件为空吗？

**Comment by LazuliKao** [comment]
如文件无法写入尝试修改此项
![image](https://user-images.githubusercontent.com/46601807/173166767-07bf3cfb-f9cf-49f6-b6b1-7d1798412711.png)

**Comment by threestarsQAQ** [comment]
行，我去试试
