### ISSUE TITLE
一直报错

### ISSUE THREAD

**Issue by threestarsQAQ** [littlegao233/PFEssentials-Release#11]
![A9BE1927-9CD9-46AE-BF1D-DC3879708CB7](https://user-images.githubusercontent.com/106313729/175865099-9804ed23-966b-4bd2-8082-f544920a7a38.jpeg)
不知道什么意思，也安装了最新的BDS和PFE

**Comment by LazuliKao** [comment]
检查下`plugins\PFEssentials\data\identity.json`

建议加群，github有时候没看到（群号mb帖子末尾
